server:
    port: 8081

spring:
  profiles:
    active: dev
  security:
    user:
      name: demo
      password: demo
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/bwa}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: bwa
  h2:
    console:
      enabled: true

springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html